name: Deploy MkDocs Site to S3

on:
  push:
    branches:
      - ci/add_gitworkflow   # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install MkDocs
      run: |
        pip install mkdocs

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # or your preferred region

    - name: Build MkDocs site
      run: |
        rm -rf site
        mkdocs build

    - name: Deploy to S3
      run: |
        aws s3 sync ./site s3://o2-github-action-s3/docs --exclude=".git/*"

    # - name: Invalidate CloudFront cache
    #   run: |
    #     aws cloudfront create-invalidation \
    #       --distribution-id EZ2SEJVXM7NXL \
    #       --paths "/docs/*"